sudo: required
services:
      - docker

before_install:
  - docker build -t sauguy/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run sauguy/react-test npm test -- --coverage

after_success:
  - docker build -t sauguy/multi-client ./client
  - docker build -t sauguy/multi-nginx ./nginx
  - docker build -t sauguy/multi-server ./server
  - docker build -t sauguy/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sauguy/multi-client
  - docker push sauguy/multi-nginx
  - docker push sauguy/multi-server
  - docker push sauguy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-077210562964
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY